apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: risto
  labels:
    app: risto
spec:
  template:
    metadata:
      labels:
        app: risto
    spec:
      containers:
        - name: risto-container
          image: "{{ .Values.markoImage }}"
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlDatabase }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
            - name: MYSQL_HOST
              value: {{ .Values.mysqlHost }}
            - name: MYSQL_PORT
              value: {{ .Values.mysqlPort }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase }}
            - name: SERVICE_PORT
              value: "80"