apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: risto
  labels:
    app: risto
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: risto
    spec:
      containers:
        - name: risto-container
          image: "{{ .Values.ristoImage }}"
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlUsername }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
            - name: MYSQL_HOST
              value: {{ .Values.mysqlHost }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase }}
            - name: SERVICE_PORT
              value: "80"